name: wriety_cli
description: A CLI tool for updating branding information.
version: 1.0.6
repository: https://github.com/elysian12/wriety_cli

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.4.2
  dcli: ^3.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
